version: "3"
services:
  bot:
    build:
      context: ./
      dockerfile: raspisator/Dockerfile
    restart: always
    env_file:
      - 'variables.env'
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - DEBUG=$DEBUG
    depends_on:
      - redis
      - mongo
    networks:
      - mongo-redis-celery
      
  worker:
    build:
      context: ./
      dockerfile: worker/Dockerfile
    env_file:
      - 'variables.env'
    depends_on:
      - redis
      - mongo
    networks:
      - mongo-redis-celery
        
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      mongo-redis-celery:
        aliases:
          - "redis"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  mongo:   
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
        mongo-redis-celery:
          aliases:
            - "mongodb"
  
networks:
  mongo-redis-celery:
    driver: bridge